services:
  db:
    image: postgres:16
    container_name: postgres_api
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: jsprint_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    image: ruby:3.3
    container_name: jsprint_api
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: bash -c "gem install rails && rails new . --api -d postgresql && bundle install && rails server -b 0.0.0.0"

volumes:
  pgdata: